sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: sOf1utgQarlGZkncr3ChqPvif/zGqb23QtqMTgwqqRrQ8eHbhYcyd9q/PXlrhcjvar1ubUBRyubyXlTKaHbQtLVNtinXTuFMIncv9+IIgHI54kb6y57fFSN+B15c46w9dBRnz3SxbALte4Rf8M4KBd2Ls9VYIGBVwStI+I18MONUrV0Hk85afSxIrz2lcX0SzOv5a1ULACh8A3yTaVaX1Z58x92NP5y19pM5aLjMs7/hxIDcpCBWpUshF4UE3AlVLOic9mVAcOIUp6ELD2KNWyQVk0pFHMufWp/G/MRILyRyI4xFo39BEsShTPfO1+0tI0MllsQzjOSIv3Ey/RHACXW9cYP9aGPUZwBF2wHtvOBVYheBlYQB5ARrLipKpBf73FBhPxjejrQYsRMsS5ymGRohSUGpz5YmFHjWMjqivpTwsbev43iNi0P+IRgU8EiG6hMxpolQ7T+EKA8PUmaMO4bFzyDYX74ag3qifiCvECzGbvpBiaTCR8jZawtEiWLcZU81XaYvz3OknExIdtXtL1qd2PbYFsayoP/mESceMS2coVK+l5riiNyDFJGnxB0IDQ3X1om/91ZxNG/AZOvNNTZvOmUyMhNB9K4Mbxd7Z6l7Gge/kggGI5A5FgQ6A7DWJQdz+e3S/7hHahmwsw/DBqA6jyzVjiuF0FKRjIY23bI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/A-Narrative-of-the-Expedition-to-Botany-Bay_3535
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy